export const gameType = {
  START_GAME_APP: "START_GAME_APP",
  START_GAME: "START_GAME",
  GET_MAP: "GET_MAP",
  UPDATE_MAP: "UPDATE_MAP",
  OPEN_CELL: "OPEN_CELL",
  FLAG_CELL: "FLAG_CELL",
  UNFLAG_CELL: "UNFLAG_CELL",
  WIN_GAME: "WIN_GAME",
  LOSE_GAME: "LOSE_GAME",
};
